name: Test Build

on:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Build
        run: |
          pip install -r requirements.txt pyinstaller
          pyinstaller --onefile --windowed `
            --hidden-import=keyring.backends.Windows `
            --hidden-import=keyring.backends.fail `
            --collect-all=customtkinter `
            app.py
          dir dist
